### ISSUE TITLE
Reflect changes made to I/O API

### ISSUE THREAD

**Issue by leemachin** [leemachin/ask_awesomely#11]
- As a temporary measure, can switch the URL to use the old version

**Comment by joshRpowell** [comment]
Hi @leemachin we've had some success using Typeform on a client project.  The demand is there to create more forms. We've been considering Typeform I/O and ask_awesomely seems like a viable tool. 

Does this issue reflect upcoming changes?

**Comment by leemachin** [comment]
Hey @joshRpowell :) thanks for using us, it's great that it's working out for you! We have [a channel on Slack](http://docs.typeform.io/v0.4/page/slack-invite) where the people involved more closely with I/O are available to chat – they will be able to give you a better answer than I can right now in terms of what's coming next, and outside of the specifics of how this library works (which is something I made in my own time) they can answer any questions you have about the service in general.

In any case our API is currently versioned and sits at `v0.4`, which is what the library uses too. The main issue it has right now is that I point the API to `/latest`, which is going to cause problems even if nothing much changes.

Does that help?
