### ISSUE TITLE
Is it possible to use a lambda in an answer?

### ISSUE THREAD

**Issue by fhinson** [leemachin/ask_awesomely#14]
Is it possible to use a lambda in an answer? For example, in a multiple choice block

`choice -> (user){"#{user.address}"}`

**Comment by leemachin** [comment]
This is possible for any field that lets you add a choice, yes :)

**Comment by fhinson** [comment]
Do you mind demonstrating correct syntax for using a lambda in a choice? Thanks.

On Thu, Apr 14, 2016 at 6:52 AM, Lee Machin <notifications@github.com> wrote:
This is possible for any field that lets you add a choice, yes :)

**Comment by leemachin** [comment]
Can you explain what the bugs are? Or post the errors if there are any? That would be helpful for me to see what is going on.

**Comment by fhinson** [comment]
I want the following field to display the user's existing email in the database as a multiple choice field.

```
field :multiple_choice do
    ask "What is your email address?"

    choice -> (user) {"#{user.email}"}
    can_specify_other
  end
```

And this is what is rendered in the Typeform:

<img width="792" alt="screen shot 2016-04-14 at 10 55 14 am" src="https://cloud.githubusercontent.com/assets/748666/14532553/6aa28662-022f-11e6-9ad1-70c712a20924.png">

**Comment by leemachin** [comment]
Ok, thanks! That shouldn't happen. I'll try and get a fix up for it today.

**Comment by fhinson** [comment]
Great, thanks!

**Comment by leemachin** [comment]
Okay, upgrading to 0.2.5 will solve your problem :)

**Comment by fhinson** [comment]
Excellent, it works! Thank you so much for resolving this quickly.
