### ISSUE TITLE
Option to disable branding?

### ISSUE THREAD

**Issue by fhinson** [leemachin/ask_awesomely#15]
As described in the typeform.io API, there is an option to disable branding on a form by passing a boolean value to a `branding` field.

Does `AskAwesomely` support this yet?

**Comment by leemachin** [comment]
Looks like I missed that setting out. It's not supported at the moment, I'll add it in as soon as I can.

As a hacky workaround in the meantime, you can probably add it directly to the internal state of the form.

```ruby
YourTypeform._state.branding = false
YourTypeform.build
```

**Comment by fhinson** [comment]
Thanks!

**Comment by leemachin** [comment]
All done. This and the other things are in a new release.
