### ISSUE TITLE
Field long_text <AskAwesomely::Field::LongText> does not exist

### ISSUE THREAD

**Issue by ZackBurtPoncho** [leemachin/ask_awesomely#21]
`AskAwesomely::FieldTypeError (Field long_text <AskAwesomely::Field::LongText> does not exist, please use one of: short_text, long_text, multiple_choice, picture_choice, statement, dropdown, yes_no, number, rating, opinion_scale, email, website, legal):
`

The offending code:

```

  field :long_text do
    say "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    tags :field_name1
    ref :field_name1
  end
```

**Comment by leemachin** [comment]
I think this is because I implemented `say` as a method only for `statement` fields (which makes a `NoMethodError`). The new release (0.2.8) changes this so you can use `say` or `ask` in any field.

**Comment by ZackBurtPoncho** [comment]
Thanks @leemachin
