### ISSUE TITLE
AskAwesomely::ConfigurationError: Typeform I/O API Key must be set before use

### ISSUE THREAD

**Issue by abrambailey** [leemachin/ask_awesomely#22]
I have the following in `initializers/ask_awesomely.rb`
```ruby
AskAwesomely.configure do |config|
  config.typeform_api_key = ENV["my_api_key"]
end
```
When I start a console and try your example:
```ruby
user = OpenStruct.new(name: "Rubyist")
typeform = MyNewTypeform.build(user)
```

I see the error: `AskAwesomely::ConfigurationError: Typeform I/O API Key must be set before use`

Where should I define my API key? Thanks.

**Comment by leemachin** [comment]
Maybe this is related to the documentation @Walid-Shouman provided in #24? It all looks correct to me - I haven't tested in a Rails set up to know if any extra tweaking is required.

One other thing, can you check the value of `ENV["my_api_key"]` to make sure it's present?

**Comment by Walid-Shouman** [comment]
@abrambailey  you may run the following command in shell before starting console
```shell
echo 'export my_api_key="the acquired api key"' >> ~/.profile && source ~/.profile
```
that will ensure your env variable is defined
