### ISSUE TITLE
Get a field ids after building form 

### ISSUE THREAD

**Issue by msoedov** [leemachin/ask_awesomely#26]
I did not find an easy way how to match from results with form questions:
This what I receive on my webhook 

``` json
{"answers":[{"field_id":4.4241236e+07,"type":"choice","value":{"label":"Example","other":null}}]...
```

And `field_id` is assigned to each question in the from. However in the api wrapper there is explicit way how to retrieve this information.

**Comment by romainmp** [comment]
You could use tags to identify questions or group of questions.

**Comment by leemachin** [comment]
Hi @msoedov, this looks like an issue with the I/O API. I'm finding out what is happening.

**Comment by msoedov** [comment]
@romainmp using tags instead of `field_id` is definitely a vehicle.

**Comment by leemachin** [comment]
@romainmp is right (and I misunderstood the problem) - a simple way to do this right now is to add tags to your form (http://docs.typeform.io/docs/tagging-introduction). This means you have a lot of control over how you identify your questions, and you can reuse those across many forms.

As a separate issue, this library could also expose the field IDs it receives when a form is built (right now it ignores them). If those were visible you would be able to compare the field IDs instead.

**Comment by msoedov** [comment]
@leemachin 
>  this library could also expose the field IDs it receives when a form is built 

This exactly what I was looking for. I believe distinguishing form builder and communication with rest api would lead to a better flexibility and library design.

> a simple way to do this right now is to add tags to your form 

I choose to write a small script which just prepare json payload and send it over raw http library. That took about 15 minutes which is better than dirty hack with tags in my opinion.  I just want emphasize that it's a great opportunity for improvement because the current way to match answers with questions is a real pain in the butt :)

**Comment by leemachin** [comment]
Pull requests are welcome ;)

**Comment by romainmp** [comment]
I guess you'd have to do that in the Typeform.update_with_api_response method. 
Any indications on how best to go through the "structure" and add a field_id to the fields?
